config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
    resources :comments
  end
  
 # Defines the root path route ("/")
  root "home#index" 
  get 'posts/new'
  get 'home/about'
  get 'posts/index'
  get '/search', to: "posts#search"
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
  end

end







  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  #get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
 # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  #get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :comments
	belongs_to :user
	
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController


	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(params[:comment].permit(:name, :comment))
		redirect_to post_path(@post)
	end 

	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy
		redirect_to post_path(@post)
	end



end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
  end

  def about
  end


  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	#before_action :set_post, only: %i[ show edit update destroy ]
	before_action :authenticate_user!, except: [:index, :show]
	before_action :correct_user, only: [:edit, :update, :destroy]

	def index
		@posts = Post.all.order("created_at DESC")
	end

	def search
		@query = params[:query]
		@posts = Post.where("posts.title LIKE ?", ["%#{@query}%"])
		render "index"
	end

	def new
		#@post = Post.new
		@post = current_user.posts.build
	end

	def create
		#@post = Post.new(post_params)
		@post = current_user.posts.build(post_params)

		respond_to do |format|
	      	if @post.save
		        format.html { redirect_to post_path(@post), notice: "Post was successfully created." }
		        format.json { render :show, status: :created, location: @post }
	      	else
		        format.html { render :new, status: :unprocessable_entity }
		        format.json { render json: @post.errors, status: :unprocessable_entity }
      		end
    	end
	end

	def show
		@post = Post.find(params[:id])
	end

	def update

		respond_to do |format|
      		if @post.update(post_params)
        		format.html { redirect_to post_path(@post), notice: "Post was successfully updated." }
        		format.json { render :show, status: :ok, location: @post }
      		else
        		format.html { render :edit, status: :unprocessable_entity }
        		format.json { render json: @post.errors, status: :unprocessable_entity }
      		end
    	end

		#@post = Post.find(params[:id])

		#if @post.update(post_params)
			#redirect_to @post
		#else
			#render 'edit'
		#end

	end


	def edit
		@post = Post.find(params[:id])
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy

		respond_to do |format|
      		format.html { redirect_to posts_path, notice: "Post was successfully destroyed." }
      		format.json { head :no_content }
		end
	end

	def correct_user
		@post = current_user.posts.find_by(id: params[:id])
		redirect_to posts_path, notice: "Not authorized to edit/delete this post" if @post.nil?
	end

	private
	
	def post_params
		params.require(:post).permit(:title, :content, :user_id)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="card">
  <div class="card-body">
    <p>
      <strong> <%= comment.name %>: </strong>
      <%= comment.comment %>
    </p>

     <%= link_to "Delete", [comment.post, comment], data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'}, class: "btn btn-danger float-right" %>

  </div>

 
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
	<div class="field form-group w-25">
  		<label for="title" class="form-label font-weight-bold">Name</label>
  		<%= f.text_field :name, class:"form-control" %>
	</div>

	 </br></br>

	<div class="form-group w-50">
  		<label for="content" class="form-label font-weight-bold">Comment</label>
  		<%= f.text_area :comment, class:"form-control" %>

	</div>

	<%= f.button :submit, class: 'btn btn-primary' %>

<%end %>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #54aecb;">
  <%= link_to 'Demo Blog', root_path, class:"navbar-brand"%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <li class="nav-item">
        <%= link_to 'About Us', home_about_path, class:"nav-link"%>
      </li>
      <li class="nav-item">
        <%= link_to 'New Post', posts_new_path, class:"nav-link"%>
      </li>
      <li class="nav-item">
        <%= link_to 'Blog Index', posts_path, class:"nav-link"%>
      </li>


      <% if user_signed_in? %>
        <li class="nav-item">
            <%= link_to 'Edit Profile', edit_user_registration_path, class:"nav-link"%>
        </li>

        <li class="nav-item">
            <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class:"nav-link"%>
        </li>

      <% else %>
        <li class="nav-item">
            <%= link_to 'Sign Up', new_user_registration_path, class:"nav-link"%>
        </li>

        <li class="nav-item">
          <%= link_to 'Sign In', new_user_session_path, class:"nav-link"%>
        </li>

      <% end %>



<!--
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Profile
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if user_signed_in? %>
            <a class="dropdown-item" href="#"><%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link"%></a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#"><%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"nav-link"%></a>
          <% else %>
            <a class="dropdown-item" href="#"><%= link_to "Sign Up", new_user_registration_path, class:"nav-link"%></a>
            <a class="dropdown-item" href="#"><%= link_to "Sign In", new_user_session_path, class:"nav-link"%></a>
        </div>
      </li>

          <% end %>

-->
          
    </ul>
    <form class="form-inline my-2 my-lg-0" method="GET" action="/search">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="query" method="GET">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About Us...</h1>
My name is Joe Preziuso and this is a Rails web application.
</br></br>
The purpose of this app is to allow users to create and view blog posts!
</br></br>
Feel free to look around and have fun!

app/views/home/index.html.erb
<h1>Hello World!</h1>
This is a Rails Webpage...It allows users to create blog posts!

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="close" data-bs-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Demo Blog App</title>
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>


    
  </head>
  <body>

    <%= render 'home/header' %>
    <div class="container">
       <br/>
        <% if notice %>
          <%= render 'layouts/alerts' %>
        <% end %>

        <%= yield %>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
    <%= javascript_include_tag "turbo", type: "module" %>
    <%= javascript_importmap_tags %>


  </body>
</html>

app/views/posts/_form.html.erb
<div class="section">
	<%= form_for(@post) do |f| %>


		 <% if @post.errors.any? %>
			<div style="color: red">
	      		<h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being created:</h2>

	      		<ul>
	        		<% @post.errors.each do |error| %>
	          		<li><%= error.full_message %></li>
	        	<% end %>
	      		</ul>
	    	</div>
	  	<% end %>

		<div class="field form-group w-25">
	  		<label for="title" class="form-label font-weight-bold">Title</label>
	  		<%= f.text_field :title, class:"form-control" %>
		</div>

		 </br></br>

		<div class="form-group w-50">
	  		<label for="content" class="form-label font-weight-bold">Content</label>
	  		<%= f.text_area :content, class:"form-control" %>

		</div>

		<div class="form-group w-25">
	  		<%= f.number_field :user_id, id: :post_user_id, class:"form-control", value: current_user.id, type: :hidden %>

		</div>

		<%= f.button :submit, class: 'btn btn-primary' %>
		<%= link_to 'Back', posts_path, class:"btn btn-dark" %>
	
		
	<% end %>

</div>

app/views/posts/_post.html.erb
<div class="container">
	<% @posts.each do |post| %>
		<% if post.user == current_user %>
			<div class="card">
				<h5 class="card-title">
					<%= link_to post.title, post %>
				<div class="card-body">
					<%= link_to 'Edit', edit_post_path(post), class:"btn btn-secondary" %>
			  		<%= link_to "Delete", post_path(post), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'}, class: "btn btn-danger" %>
				  	<%= link_to 'Back', posts_path, class:"btn btn-dark" %>
			  	</div>
		  	</div>
	  	<% end %>
  	<% end %>
</div>

app/views/posts/edit.html.erb
<h1> Editing Post </h1>
<br/>
<%= render 'form' %>

<br/>

app/views/posts/index.html.erb
<h1 class="title">Blog Index<h1>


<section class ="section">
	<div class="container">
		<% @posts.each do |post| %>
			<% if post.user == current_user %>
			<div class="card">
				<div class="card-body">
					<h5 class="card-title"><%= link_to post.title, post %></h5>
					<p class="h6"> <%= post.content %></p>
					<!-- <a href="#" class="btn btn-primary">Go somewhere</a> -->
				</div>
			</div>
			<% end %>
		<% end %>
	</div>
</section>

	

app/views/posts/new.html.erb
<h1 class="title">New Post</h1>

</br>


<%= render 'form', post: @post %>


<!--

<div class="section">
	<%= form_for(@post) do |f| %>

		<div class="field form-group w-25">
	  		<label for="title" class="form-label font-weight-bold">Title</label>
	  		<%= f.text_field :title, class:"form-control" %>
		</div>

		 </br></br>

		<div class="form-group w-50">
	  		<label for="content" class="form-label font-weight-bold">Content</label>
	  		<%= f.text_field :content, class:"form-control form-control-lg" %>
		</div>

		<%= f.submit 'Create new post', class: 'btn btn-primary' %>
	
	<% end %>

</div>
-->

app/views/posts/search.erb
<h1>Search Results</h1>

<%= render @posts %>

app/views/posts/search.html.erb
<h1>Search Results</h1>

<%= render @posts %>

app/views/posts/show.html.erb
<div class="jumbotron">
  <h1 class="display-4">
  	<%= @post.title %>
  </h1>

  <p class="lead">
  	<%= @post.content %>
  </p>

  
  <hr class="my-4">
    <%= link_to 'Edit', edit_post_path(@post), class:"btn btn-secondary" %>
  	<%= link_to "Delete", post_path(@post), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'}, class: "btn btn-danger" %>
	  <%= link_to 'Back', posts_path, class:"btn btn-dark" %>
</div>




<section class="section comments">
  <div class="container">
    <h4 class="subtitle is-5"><strong><%= @post.comments.count %></strong> Comments </h4>
    <%= render @post.comments %>
    <div class="comment-form">
      <hr />
      <h5 class="subtitle is-3"> Leave a reply</h5>
      </br>
      <%= render 'comments/form' %>
  </div>
</section>











<!--
<div class="modal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title"><%= @post.title %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p><%= @post.content %></p>
      </div>
      <div class="modal-footer">
        <%= link_to 'Edit', edit_post_path(@post), class:"btn btn-secondary" %>
        <%= link_to "Delete", @post, data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'}, class: "btn btn-danger" %>
        <%= link_to 'Back', posts_path, class:"btn btn-dark" %>
      </div>
    </div>
  </div>
</div>
-->